FROM node:alpine3.10

# S2I Environment variables
ENV NPM_RUN=start \
  DEBUG_PORT=5858 \
  STI_SCRIPTS_PATH=/usr/libexec/s2i \
  APP_ROOT=/opt/app-root \
  HOME=/opt/app-root/src \
  PATH=$APP_ROOT/bin:$HOME/bin:$HOME/node_modules/.bin/:$PATH \
  NPM_CONFIG_PREFIX=$HOME/.npm-global \
  NODE_ENV=production \
  DEV_MODE=false \
  BUILDER_VERSION=1.0

LABEL io.k8s.description="Platform for building Node.JS application" \
  io.k8s.display-name="Node.JS builder ${BUILDER_VERSION}" \
  io.openshift.expose-services="8080:http" \
  io.openshift.tags="node,npm,builder" \
  io.openshift.s2i.scripts-url="image://$STI_SCRIPTS_PATH" \
  io.s2i.scripts-url="image://$STI_SCRIPTS_PATH" \
  name="s2i-node"

# Prepare directories
RUN mkdir /src && \
  mkdir /opt/usr && \
  mkdir -p $APP_ROOT && \
  mkdir -p $HOME && \
  mkdir -p $HOME/.npm-global && \
  mkdir -p $STI_SCRIPTS_PATH

# Install dependencies
RUN apk update && apk upgrade && apk add --no-cache \
  bash curl ca-certificates openssl tar unzip git && \
  rm -rf /var/cache/apk/*

# Copy s2i scripts
COPY ./s2i/bin/ $STI_SCRIPTS_PATH

ENV BASH_ENV=$APP_ROOT/etc/scl_enable \
  ENV=$APP_ROOT/etc/scl_enable \
  PROMPT_COMMAND=". $APP_ROOT/etc/scl_enable"

RUN adduser -u 1001 -S -G root -h ${HOME} -s /sbin/nologin default && \
  chown -R 1001:0 $APP_ROOT && \
  chown -R 1001:0 $STI_SCRIPTS_PATH && \
  chown -R 1001:0 /opt/usr && \
  chown -R 1001:0 /src

USER 1001

EXPOSE 8080

WORKDIR ${HOME}

CMD $STI_SCRIPTS_PATH/usage